openapi: "3.0.0"
info:
  version: 1.0.0
  title: JSONPlaceholder
  license:
    name: MIT
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      summary: List of all posts
      operationId: getPosts
      tags:
        - posts
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /posts/{id}:
    get:
      summary: Get a post
      operationId: getPost
      tags:
        - posts
      parameters:
        id:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

components:
  schemas:
    Post:
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        title:
          type: string
        body:
          type: string
